"""Per-corridor train lists, generated by the goods-scheduling process (see
docs/input-generation.md) and converted to JSON by scripts_migration_convert_schedules.py.
"""
from .loader import load_trains, available_corridors

__all__ = ["load_trains", "available_corridors"]
